Work
KevinLaCarrubba/Portfolio pull request #1
Opened 2021-12-03 20:00 UTC by KevinLaCarrubba

Ooo LaLa

2021-12-03 20:15 UTC, arfusop requested changes

2021-12-03 20:15 UTC, arfusop commented on portfolio/public/index.html
> +    <title>React App</title>
Update this to your actual page title

2021-12-03 20:15 UTC, arfusop commented on portfolio/src/App.css
> +/* css for the header */
This is all fine and well if our standards are WAY lower. Section everything into its own `[componentname].module.css` file and apply them to their respective components. I can help when you want

2021-12-03 20:15 UTC, arfusop commented on portfolio/src/App.css
> +/* css for the header */
The only thing that should live in here is what is considered global styling

2021-12-03 20:15 UTC, arfusop commented on portfolio/src/App.js
> +    <Router>
Isn't this website going to be only one page with scrolling through views? Never `routing` off of the main url? If so, remove and uninstall `react-router-dom` cuz it's not needed to accomplish what you want

2021-12-03 20:15 UTC, arfusop commented on portfolio/src/components/Body/AboutMe.js
> +    </>
Instead of what you have here, do this:

```
<div>
  <h1 className="aboutMe">About Me</h1>
  <p className="aboutMe">Yer Im Kevin Add info here.</p>
</div>
```

2021-12-03 20:15 UTC, arfusop commented on portfolio/src/components/Body/Contact.js
> +      {/* add icons for links */}
Also, convert the `p` to this: `<a href="site" target="_blank"><p><icon /></p></a>`

2021-12-03 20:15 UTC, arfusop commented on portfolio/src/components/Body/Project.js
> +        {/* make a component to view projects */}
🔥

2021-12-03 20:15 UTC, arfusop commented on portfolio/src/components/Footer.js
> +      <footer className="footer">PARfuso Taught Dat Footer</footer>
YER

2021-12-03 20:15 UTC, arfusop commented on portfolio/src/components/Header.js
> +    <div>
Since your structure is: div -> header -> all children, you can remove the div entirely. The div is redundant and not needed, the header acts as the parent wrapping everything.

```
<header>
  [children]
</header>
```

2021-12-03 20:43 UTC, bartlomein commented on portfolio/src/App.css
> +/* css for the header */
phil is my son

2021-12-03 20:44 UTC, bartlomein commented on portfolio/src/App.js
> +    <Router>
phils is my son

2021-12-03 20:44 UTC, bartlomein commented on portfolio/src/components/Body/AboutMe.js
> +    </>
phil is my son

2021-12-03 20:45 UTC, bartlomein commented on portfolio/src/components/Body/Contact.js
> +      {/* add icons for links */}
phil is my son

2021-12-03 20:45 UTC, bartlomein commented on portfolio/src/components/Body/Project.js
> +        {/* make a component to view projects */}
phil is my son

2021-12-03 20:46 UTC, bartlomein commented on portfolio/src/components/Footer.js
> +      <footer className="footer">PARfuso Taught Dat Footer</footer>
phil is my son

2021-12-03 20:46 UTC, bartlomein commented on portfolio/src/components/Header.js
> +    <div>
phil is my son

2021-12-03 20:48 UTC, bartlomein commented on portfolio/public/index.html
> +    <title>React App</title>
phil is my son

2021-12-04 20:16 UTC, KevinLaCarrubba commented on portfolio/src/components/Footer.js
> +      <footer className="footer">PARfuso Taught Dat Footer</footer>
yerrr

2021-12-04 20:47 UTC, merged