Work
KevinLaCarrubba/Portfolio pull request #2
Opened 2021-12-04 21:41 UTC by KevinLaCarrubba

not gonna tell you about why i couldnt push from branch work to branch Work ... learning pains include capitals and colons

2021-12-04 22:54 UTC, arfusop commented on portfolio/src/components/Body/Contact/Contact.js
>        <a href="#" target="_blank">
You dont need a paragraph inside the anchor that holds an SVG element. Just do `<a><Icon/></a>`

2021-12-04 23:02 UTC, arfusop requested changes

2021-12-04 23:02 UTC, arfusop commented on portfolio/src/components/Body/Project/Project.js
> +      <ProjectDisplay />
Remove the `<> </>`, move the `ProjectDisplay` into the `div.projectContainer`. Use that div as the wrapper element for this entire component

2021-12-04 23:02 UTC, arfusop commented on portfolio/src/components/Body/Project/ProjectDisplay.js
> +import project from "./_projectDisplay.module.css";
Update the variable for your `project` styles to `styles`, common convention. If there's ever multiple css module files imported to one component, you'd want to name them as `projectStyles` and `[otherDescriptiveName]Styles`, but we'll cross that bridge when we get there

2021-12-06 00:12 UTC, arfusop requested changes

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Body/Contact/_contact.module.css
> +/* .container {
Get rid of commented out code. CSS you can very easily recreate, no need to clutter the code up 😆

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Body/Contact/Contact.js
> +    <section id="contact" className={styles.contact}>
This ID is not needed

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Body/Contact/Contact.js
> +        <a href="#" target="_blank" className={styles.icon1}>
all of these `a` tags have a common theme, you want to apply very similar to the same styling in the children of all of them. Add an `id="icon[number]` to each, and give them all the same class: `iconLinks` (or whatever class name you want it to be. Then in the CSS, apply the `grid-area` by ID, and then apply the following styling
```
  text-decoration: none;
  display: flex;
  align-items: center;
  color: white;
  height: 100%;
  width: 100%;
```
to the general, reused class for all of the anchor tags

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Body/Contact/_contact.module.css
>  .contact {
Move all of the styles outside of `.contact` inside, nest appropriately

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Body/Contact/_contact.module.css
> +.icon1 {
Do what i said in the above PR about adding IDs, combining the styles. Then move these all nested under the `.container`, so this should be three levels deep of nesting at this point

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Body/Contact/_contact.module.css
> +.quote {
nest inside of `.container` as well

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Body/Contact/_contact.module.css
> +/* .link {
delete

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Body/Contact/_contact.module.css
> +.icons {
nest

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Body/Contact/_contact.module.css
> +.iconText {
nest

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Body/Navbar/_navbar.module.css
> +.navbar {
nest everything properly

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Body/Project/_project.module.css
> +.title {
nest

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Body/Project/_projectDisplay.module.css
> +.imageTitle {
nest

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Footer/Footer.js
> +  return <div></div>;
If you're not using the footer at all, delete. If you plan to add a footer, ignore this for now

2021-12-06 00:12 UTC, arfusop commented on portfolio/src/components/Header/_header.module.css
>  .header {
nestttttt

2021-12-06 15:38 UTC, KevinLaCarrubba commented on portfolio/src/App.js
>      </main>
footers fucked

2021-12-06 15:58 UTC, KevinLaCarrubba commented on portfolio/src/components/Body/AboutMe/_aboutme.module.css
> +  color: rgba(24, 170, 151, 1);
all colored up

2021-12-06 15:58 UTC, KevinLaCarrubba commented on portfolio/src/components/Body/Navbar/_navbar.module.css
> +.navbar {
take it ease with the nest

2021-12-06 15:58 UTC, KevinLaCarrubba commented on portfolio/src/components/Body/Project/_project.module.css
> +.title {
i said take it ease

2021-12-06 15:59 UTC, KevinLaCarrubba commented on portfolio/src/components/Footer/Footer.js
> +  return <div></div>;
footer be gone

2021-12-06 15:59 UTC, KevinLaCarrubba commented on portfolio/src/components/Header/_header.module.css
>  .header {
I SAID TAKE IT EASY .. hold my grey !

2021-12-06 16:03 UTC, KevinLaCarrubba commented on portfolio/src/components/Body/AboutMe/AboutMe.js
> +    <section id="profile" className={styles.profile}>
IDs have left the building .. make way for smooth scrolling

2021-12-06 16:04 UTC, KevinLaCarrubba commented on portfolio/src/components/Body/Contact/_contact.module.css
> +/* .container {
Win Guardian Live E OH Sah . its gone

2021-12-06 16:04 UTC, KevinLaCarrubba commented on portfolio/src/components/Body/Contact/Contact.js
> +    <section id="contact" className={styles.contact}>
poof

2021-12-06 16:12 UTC, KevinLaCarrubba commented on portfolio/src/components/Body/Contact/Contact.js
> +        <a href="#" target="_blank" className={styles.icon1}>
didnt think to use ID

2021-12-06 16:13 UTC, KevinLaCarrubba commented on portfolio/src/components/Body/Contact/_contact.module.css
> +.iconText {
you and the nest

2021-12-06 16:16 UTC, arfusop approved these changes

2021-12-06 16:17 UTC, merged